service:
  image: vsftpd
  depends: []
  dockerargs: ["--network","host", "-e", "PASSWORD=secret"]
  mount:
  - etc/vsftpd
  - opt/ftp:/home/files
  ports: [] # no ports exported, as we use `--network host`
