service:
  image: nginx
  depends: []
  mount:
  - etc/letsencrypt
  - etc/nginx/conf.d
  - services/nginx/hooks
  - opt/ftp
  ports:
  - 10080:10080/tcp
  - 10443:10443/tcp
  - 10444:10444/tcp
  - 443:443/tcp
